"""check for any new

Revision ID: 7bde7d312a86
Revises: a8021af6fec3
Create Date: 2022-04-16 21:38:03.531620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bde7d312a86'
down_revision = 'a8021af6fec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
