"""auto generate

Revision ID: a8021af6fec3
Revises: 46a534ed00d8
Create Date: 2022-04-16 21:18:09.502016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8021af6fec3'
down_revision = '46a534ed00d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
