"""whether autogenerate test_id

Revision ID: e5b1e79a58d1
Revises: 7bde7d312a86
Create Date: 2022-04-19 22:36:23.266304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b1e79a58d1'
down_revision = '7bde7d312a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
